apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

patches:
- path: minimum-replicas.yaml
  target:
    kind: Deployment
- path: patch-deployment.yaml
  target:
    kind: Deployment
