apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

# Références au fichier de patch
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
images:
- name: pokedex
  newName: ghcr.io/zalmaxx/pokedex
  newTag: sha-c3cc788
