apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

images:
  - name: pokedex:1.0.0
    newTag: "1.0.0"

# Références au fichier de patch
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: guestbook-ui